[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.install]
cmds = ['cd IdentityService && chmod +x mvnw']

[phases.build]
cmds = ['cd IdentityService && ./mvnw clean package -DskipTests']

[start]
cmd = 'cd IdentityService && java -jar target/IdentityService-0.0.1-SNAPSHOT.jar'