[phases.setup]
nixPkgs = ['maven', 'jdk17']

[phases.build]
cmds = ['chmod +x IdentityService/mvnw', 'cd IdentityService && ./mvnw clean package -DskipTests']

[start]
cmd = 'java -jar IdentityService/target/IdentityService-0.0.1-SNAPSHOT.jar'